# Numpy

In [1]:
#pip install numpy

In [2]:
import numpy as np

In [3]:
L1 = [1, 2, 3, 4, 5, 6 ,7, 8, 9, 10]
L1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [4]:
x1 = np.array(L1)
x1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
x2 = np.array(L1, dtype='float32')
x2

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

- float32
- int_, intc, intp, int8, int16, int32, int64 
- uint8, uint16, unit32, uint64
- float, float16, float32, float64 
- complex_, complex64, complex128 (a+bi, a,b $\in$ float_)

In [6]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [8]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(3,12,dtype=float)

array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [11]:
np.arange(4,5,0.1) # crea un array de 4 a 5 con saltos de 0.1

array([4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [12]:
np.linspace(1.,7.,12) # crea un array de 1 a 7 con 12 elementos

array([1.        , 1.54545455, 2.09090909, 2.63636364, 3.18181818,
       3.72727273, 4.27272727, 4.81818182, 5.36363636, 5.90909091,
       6.45454545, 7.        ])

In [13]:
np.eye(5) # crea una matriz identidad de 5x5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
x = np.zeros((8,3))
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
x.reshape(6,4) # cambia la forma de la matriz a 6x4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
x = np.arange(24)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [17]:
x.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [18]:
x.reshape(2,3,4) # cambia la forma de la matriz a 2x3x4

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [19]:
x = np.array([[1,2,3,4],[5,6,7,8]])
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
np.ravel(x) # convierte la matriz en un array

array([1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
x.flatten() # convierte la matriz en un array, crea una copia

array([1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
print(x)
np.transpose(x) # transpone la matriz

[[1 2 3 4]
 [5 6 7 8]]


array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [23]:
np.resize(x,(5,3)) # cambia el tamaño de la matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 1],
       [2, 3, 4],
       [5, 6, 7]])

In [24]:
np.append(x,[9,10,11,12]) # agrega elementos al array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [25]:
x = np.arange(12)
x = x.reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
x.ndim # dimensiones de la matriz

2

In [27]:
x.shape # forma de la matriz

(3, 4)

In [28]:
x.size # tamaño de la matriz (mxn)

12

In [29]:
x.dtype # tipo de datos de la matriz

dtype('int64')

In [30]:
x.itemsize # tamaño en bytes de cada elemento de la matriz

8

In [31]:
x.data # buffer de la matriz, dirección de memoria

In [32]:
x[2] # accede a la fila 2

array([ 8,  9, 10, 11])

In [33]:
x[2,1] # accede al elemento de la fila 2 columna 1

np.int64(9)

In [34]:
print(x)
x.shape = (4,3) # cambia la forma de la matriz
x

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [35]:
x[1:3, 0:2] # accede a las filas 1 y 2, columnas 0 y 1

array([[3, 4],
       [6, 7]])

In [37]:
y = np.arange(12)
y 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [38]:
y[3:8] # accede a los elementos de la posición 3 a 7

array([3, 4, 5, 6, 7])

In [39]:
y[1:7:2] # accede a los elementos de la posición 1 a 6 con saltos de 2  

array([1, 3, 5])

In [40]:
z = np.arange(10,6,-1)
z

array([10,  9,  8,  7])

In [41]:
y[z] # accede a los elementos de y en las posiciones de z

array([10,  9,  8,  7])

In [42]:
x = np.arange(50)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [43]:
x[x > 30] # accede a los elementos de x mayores a 30

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49])

In [44]:
cond = x < 25
cond

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])

In [45]:
x[cond] # accede a los elementos de x menores a 25

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [46]:
x[12:24] = 1 # asigna el valor 1 a los elementos de la posición 12 a 23
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [48]:
x[13 :16] = [6,9,12] # asigna los valores 6, 9 y 12 a las posiciones 13, 14 y 15
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  6,  9, 12,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [49]:
x.dtype

dtype('int64')

In [50]:
x[5] = 3.1415 # si el array es tipo entero, se redondea el valor
x

array([ 0,  1,  2,  3,  4,  3,  6,  7,  8,  9, 10, 11,  1,  6,  9, 12,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

## Copias y vistas de arrays

In [52]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
y = x
y.shape = 2,5
y 

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [56]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [57]:
z = x.copy() # crea una copia del array
z

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [58]:
z is x

False

In [59]:
y is x

True

In [60]:
t = x.view() # crea una vista del array
t

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [62]:
t.shape = (5,2)
t

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [63]:
s = x[0:2, 1:3] # crea una vista del array
s

array([[1, 2],
       [6, 7]])

In [65]:
s[:] = 5
s

array([[5, 5],
       [5, 5]])

In [66]:
s is x

False

## Funciones Universales (ufunc)

- Unarias: sqrt, sin, cos, **2
- Binarias: maximun, minimum

In [67]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
x + 3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [69]:
x - 3

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6])

In [70]:
x*3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [71]:
x/3

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [72]:
alpha = np.linspace(0, 2*np.pi, 4)
alpha

array([0.        , 2.0943951 , 4.1887902 , 6.28318531])

In [73]:
np.sin(alpha)

array([ 0.00000000e+00,  8.66025404e-01, -8.66025404e-01, -2.44929360e-16])

In [74]:
np.cos(alpha)

array([ 1. , -0.5, -0.5,  1. ])

In [75]:
np.tan(alpha)

array([ 0.00000000e+00, -1.73205081e+00,  1.73205081e+00, -2.44929360e-16])

In [76]:
np.exp(x) 

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [77]:
np.exp2(x)

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128., 256., 512.])

In [78]:
np.power(3,x)

array([    1,     3,     9,    27,    81,   243,   729,  2187,  6561,
       19683])

In [79]:
np.power(x, 2)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [80]:
np.log(x)

C:\Users\dg_su\AppData\Local\Temp\ipykernel_20604\1277889159.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(x)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [81]:
np.log2(x)

C:\Users\dg_su\AppData\Local\Temp\ipykernel_20604\3275510840.py:1: RuntimeWarning: divide by zero encountered in log2
  np.log2(x)


array([      -inf, 0.        , 1.        , 1.5849625 , 2.        ,
       2.32192809, 2.5849625 , 2.80735492, 3.        , 3.169925  ])

In [82]:
np.log10(x)

C:\Users\dg_su\AppData\Local\Temp\ipykernel_20604\1114196279.py:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(x)


array([      -inf, 0.        , 0.30103   , 0.47712125, 0.60205999,
       0.69897   , 0.77815125, 0.84509804, 0.90308999, 0.95424251])

In [83]:
np.sum(x)

np.int64(45)

In [84]:
np.nansum(x)

np.int64(45)

In [85]:
np.cumsum(x)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [86]:
np.prod(x)

np.int64(0)

In [87]:
np.mean(x)

np.float64(4.5)

In [88]:
np.median(x)

np.float64(4.5)

In [89]:
np.max(x)

np.int64(9)

In [90]:
np.min(x)

np.int64(0)

In [91]:
np.std(x)

np.float64(2.8722813232690143)

In [92]:
np.var(x)

np.float64(8.25)

In [93]:
np.argmin(x)    # índice del valor mínimo

np.int64(0)

In [94]:
np.argmax(x)    # índice del valor máximo

np.int64(9)

In [95]:
np.percentile(x, q=0.95) # percentil 95

np.float64(0.08549999999999999)

In [96]:
np.any(x) # algún valor es verdadero

np.True_

In [97]:
np.all(x) # todos los valores son verdaderos

np.False_

In [100]:
z = np.random.random((3,5))
z

array([[0.74723331, 0.12797478, 0.11937043, 0.16222432, 0.76940345],
       [0.30918289, 0.86302759, 0.21253795, 0.19726391, 0.90302883],
       [0.00871477, 0.1650068 , 0.30791571, 0.81334928, 0.73272585]])

In [103]:
z.sum() # suma de todos los elementos

np.float64(6.438959878276709)

In [104]:
z.sum(axis=0) # suma de las columnas

array([1.06513097, 1.15600918, 0.63982409, 1.17283752, 2.40515813])

In [105]:
z.sum(axis=1) # suma de las filas   

array([1.92620629, 2.48504117, 2.02771242])

In [ ]:
np.random.seed(0) # semilla para reproducibilidad