# Matrices:

In [1]:
import numpy as np

In [3]:
row = [1, 2, 3]
row

[1, 2, 3]

In [4]:
col = [[1], [2], [3]]  
col

[[1], [2], [3]]

In [5]:
M = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
M

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
M[1][1] # segunda fila y segunda columna 

5

In [7]:
M[0][0]

1

In [8]:
2*M

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=float)
M

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [11]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.shape(M)

(3, 3)

In [14]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[3, 0], [1, -1]])

In [15]:
A + B

array([[4, 2],
       [4, 3]])

In [16]:
A * B

array([[ 3,  0],
       [ 3, -4]])

In [17]:
A.dot(B)

array([[ 5, -2],
       [13, -4]])

In [18]:
A.transpose()

array([[1, 3],
       [2, 4]])

In [20]:
A.trace() # traza de la matriz

np.int64(5)

In [21]:
np.linalg.matrix_rank(A) # rango de la matriz

np.int64(2)

In [22]:
np.linalg.matrix_power(A, 5) # potencia de la matriz

array([[1069, 1558],
       [2337, 3406]])

In [23]:
np.linalg.det(A) # determinante de la matriz

np.float64(-2.0000000000000004)

In [24]:
np.linalg.inv(A) # inversa de la matriz

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [25]:
np.linalg.inv(A).dot(A) # matriz identidad

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [27]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
np.linalg.det(x)

np.float64(0.0)

In [30]:
M[0] # primera fila

array([1., 2., 3.])

In [31]:
for row in M:
    print(row[0])

1.0
4.0
7.0


In [32]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])